### ISSUE TITLE
ViewController appears under the NavigationBar

### ISSUE THREAD

**Issue by javiermanzo** [tgyhlsb/THTinderNavigationController#15]
Hi,
I add my viewcontrollers from the storyboard to the paggedViewControllers and the viewcontrollers appears under the navigationbar and I can't fix it.

**Comment by Ankish** [comment]
Yes I see the same issue. All the view controller first time are under navigation controller . It breaks the first time UI experience.

**Comment by Ankish** [comment]
Any solution to this ?
